name: GitHub Actions Demo # название action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 # заголовок в списке actions
on: # когда будет отрабатывать
  pull_request: # для всех пул, таких что
    branches: # для всех веток, таких что
      - '*' # любых
  push:
    branches:
      - 'master'

jobs: # пул задач
  init: # job
    runs-on: ubuntu-latest # прогон на последней убунту
    steps: # шаги-jobs
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Maven Package
        run: mvn -B clean package
  test:
    runs-on: ubuntu-latest
    needs: init # ПОСЛЕДОВАТЕЛЬНОЕ выполнение job'ов (без - параллельное)
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Maven test Package
        run: mvn -B test